spring:
  config:
    activate:
      on-profile: "local-database"
  application:
    name: expert
  datasource:
    url: jdbc:mysql://${DB_HOST}:3306/expert
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  cloud:
    aws:
      credentials:
        access-key: ${ACCESS_KEY}
        secret-key: ${SECRET_KEY}
      s3:
        bucketName: ${BUCHET_NAME}
      region:
        static: ap-northeast-2
      stack:
        auto: false

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: TRACE

jwt:
  secret:
    key: ${JWT_SECRET_KEY}


